### PR TITLE
 Changes to be committed:

### PR DESCRIPTION
**Pull request by DovarFalcone**
modified:   detailsPuller.py
	modified:   eventPuller.py
	modified:   wavePuller.py

Importing datetime to replace pandas datetime. Will no longer receive the warning 

"FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead."

Also cleaned up the csv file names to avoid naming errors caused by : and . characters.

Should no longer receive this error type when creating the csv files:

"OSError: [Errno 22] Invalid argument: 'waveData_Pressure2022-12-20 10:54:02.826955.csv'"

### CODE REVIEW

**Comment by Ryush806** [comment]
I think those are good fixes for the datetime issues. I'd like to get your thoughts on one thing. I don't remember adding the datetime aspect to the file naming but I obviously did. Is it really even needed? I personally would not keep multiple copies of largely the same data in CSVs. The datetime in the filename may not really be needed. And if someone really wanted it they could add a bit of code to put it in there.

**Comment by DovarFalcone** [comment]
Thanks, the date time being put in the name maybe helpful for the wave puller, where it makes multiple csvs due to pandas limitations. But for the events puller its not necessary. Just naming it `resultPath = 'eventsHistory.csv'`  would work fine. 

What I've started to do is have these scripts return data frames, then I can use the data frames for further analysis, export them to csv, or upload them to a local PostgreSQL dB when running the full set puller on details and events. 

`detailsdf = pd.DataFrame(detailsPuller(dbPath))`
`eventsdf = pd.DataFrame(eventPuller(sdPath)) `

Also, how did you figure out the file schema from the sd card for the `evenPuller.py` script. That works too cool!

**Comment by Ryush806** [comment]
I've actually started parsing the wave puller data on demand while using some analysis / visualization tools. There's just too much data after many months to effectively do anything with all the data at once. Plus it's hard to see any detail when you have more than a few nights. Any high level summary stats are already contained in the details puller output. 

One thing I have been working on is trying to quantify the extend of restriction with flow limitations. I have Upper Airway Resistance Syndrome as opposed to OSA so I have 90+% flow limitations with the occasional hypopnea and very rare apnea. Haven't made much progress because I've been busy at work but trying to figure out how much my restricted breaths deviate from my normal ones. Then maybe I can see if increased pressure helps. So far, it seems as if the flow limitations happen no matter the pressure but maybe they're less severe at higher pressure?

As far as figuring out the SD card, I did a lot of exploring with Hex Editor Neo for all the files on the SD. It was very difficult to figure out the more detailed data so when I found the patient database I switched to that method. But the events were pretty straightforward and for some reason not stored in the database. They're just text (once parsed by the editor anyway) so it was easy for a human to read. I used the terrible iMatrix software to look at some nights to figure out which ID corresponded to which type of event and also noticed that DR is duration in seconds. DT is just the UTC timestamp. Still haven't figured out what GD is but it's always zero on my data so I gave up. 

Example editor parsed EV data:

ID=19,DT=1659742367,DR=16,GD=0,
ID=17,DT=1659742370,DR=14,GD=0,
ID=17,DT=1659742753,DR=19,GD=0,
ID=20,DT=1659744394,DR=2,GD=0,

**Comment by DovarFalcone** [comment]
Oh wow, you do have an interesting case. That level of detail would be useful to find your restriction, but your right, anything more than 12 hours is a large amount of data to handle at once with just a single data frame. Are you thinking there could be a way to feed partitioned wave puller data into a model that could identify your restricted breaths? It could look at how long the pressure was increased and the frequency over time. 

The iMatrix software is a hot mess but does the job decently enough. My gd column is also always 0. I wonder if it might be for a pulse ox reading since I don't measure that. I have mild OSA so I like to try and see are there days of the week that have less events or a longer use time. I've had it for about 3 months now and feel like I'm still getting used to it. But some nights are great! So I'm trying to see what makes those nights so much better than others.

**Comment by Ryush806** [comment]
Yeah probably have whatatever analysis done whenever the smaller chunk of wave data is pulled. Whatever metric I come up with, I might try to add log it through time even if I only do one day at a time. Would be nice to see my restriction metric through time just like AHI etc. 

I found a random patent where they tried to look at the first and second derivative of the flow data. Basically to see if the inspiratory flow was flattened somehow. They were just trying to classify a flow limitation rather than degree of restriction but I think I might be able to alter it slightly to get degree. Haven't even attempted to implement it yet though.

**Review by Ryush806 — APPROVED** [review]

**Pull request merged**
